@E_Commerce.API_HostAddress = http://localhost:5132
@id = 10
GET {{E_Commerce.API_HostAddress}}/api/weatherforecast/
Accept: application/json

### Get All Products
GET {{E_Commerce.API_HostAddress}}/api/Products

### Get All Brands
GET {{E_Commerce.API_HostAddress}}/api/Products/Brands

### Get All Types
GET {{E_Commerce.API_HostAddress}}/api/Products/Types

### Get Product BY Id
GET {{E_Commerce.API_HostAddress}}/api/Products/{{id}}
